import type { Metadata } from 'next';
import localFont from 'next/font/local';
import SessionProviderWrapper from './api/auth/[...nextauth]/SessionProviderWrapper';
import ThemeProviderWrapper from './providers/ThemeProvider/ThemeProviderWrapper';
import './global/styles.scss'
import { StoreProvider } from './providers/StoreProvider';
import { auth } from './api/auth/[...nextauth]/auth';

export const metadata: Metadata = {
    title: 'Task manager',
    description: 'Generated by create next app',
};

const myFont = localFont({
    src: [
        {
            path: './global/fonts/Rubik/Rubik-Light.ttf',  // Путь к шрифту Light
            weight: '300',
            style: 'normal',
        },
        {
            path: './global/fonts/Rubik/Rubik-Regular.ttf',  // Путь к шрифту Regular
            weight: '400',
            style: 'normal',
        },
        {
            path: './global/fonts/Rubik/Rubik-Bold.ttf',  // Путь к шрифту Bold
            weight: '700',
            style: 'normal',
        },
    ],
    display: 'swap',  // Используйте "swap" для того, чтобы быстро показывать контент даже если шрифт не загружен
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    const session = auth();
    return (
        <html lang="ru">
            <SessionProviderWrapper session={session}>
                <StoreProvider>
                    <ThemeProviderWrapper>
                        <body className={myFont.className}>{children}</body>
                    </ThemeProviderWrapper>
                </StoreProvider>
            </SessionProviderWrapper>
        </html>
    );
}