import type { Metadata } from 'next';
import localFont from 'next/font/local';
import SessionProviderWrapper from './api/auth/[...nextauth]/SessionProviderWrapper';
import { getServerSession } from 'next-auth';
import ThemeProviderWrapper from './providers/ThemeProvider/ThemeProviderWrapper';
import './global/styles.scss'
import { StoreProvider } from './providers/StoreProvider';

export const metadata: Metadata = {
    title: 'Task manager',
    description: 'Generated by create next app',
};

const myFont = localFont({
    src: [
        {
            path: './global/fonts/Roboto-Thin.ttf',
            weight: '100',
            style: 'normal',
        },
        {
            path: './global/fonts/Roboto-Light.ttf',
            weight: '300',
            style: 'normal',
        },
        {
            path: './global/fonts/Roboto-Regular.ttf',
            weight: '400',
            style: 'normal',
        },
        {
            path: './global/fonts/Roboto-Bold.ttf',
            weight: '700',
            style: 'normal',
        },
    ],
    display: 'swap',
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    const session = getServerSession();
    return (
        <html lang="ru">
            <SessionProviderWrapper session={session}>
                <StoreProvider>
                    <ThemeProviderWrapper>
                        <body className={myFont.className}>{children}</body>
                    </ThemeProviderWrapper>
                </StoreProvider>
            </SessionProviderWrapper>
        </html>
    );
}